version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: monarc_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: monarc
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: monarc_common
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monarc_network

  apache:
    build: .
    container_name: monarc_apache
    ports:
      - "8080:80"
    volumes:
      - web_data:/var/lib/monarc
    networks:
      - monarc_network
    depends_on:
      - mariadb

volumes:
  db_data:
  web_data:

networks:
  monarc_network:
